services:
  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    container_name: verdakra-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      # MongoDB Atlas connection string
      - MONGO_URI=${MONGO_URI}
    volumes:
      - ./Backend:/app
      - /app/node_modules
    networks:
      - verdakra-network
    restart: unless-stopped

  code-execution:
    build:
      context: ./Backend
      dockerfile: Dockerfile.code-execution
    container_name: verdakra-code-execution
    ports:
      - "8001:8000"
    environment:
      - NODE_ENV=production
      # MongoDB Atlas connection string
      - MONGO_URI=${MONGO_URI}
      - PORT=8000
    volumes:
      - ./Backend/code-execution:/app/code-execution
      - ./Backend/models:/app/models
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - verdakra-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: verdakra-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - verdakra-network
    restart: unless-stopped

networks:
  verdakra-network:
    driver: bridge
